name: 'GitHub Tag'
description: 'Bump and push git tag'
inputs:
  default_bump:
    description: "Which type of bump to use when none explicitly provided (default: `minor`)."
    required: false
    default: 'minor'
outputs:
  new_version:
    description: "Generated tag"
    value: ${{ steps.next-version.outputs.next-version }}
runs:
  using: "composite"
  steps:
    - run: git pull --tags
      shell: bash
    - id: next-version
      run: echo "::set-output name=next-version::$(${{ github.action_path }}/nextVersion.sh)"
      shell: bash
    - run: |
        version="{{ steps.next-version.outputs.new-version }}"
        git tag -am "Auto-tagged version '$version'" "$version"
        branch=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
        git push origin "$branch" "$version"
